version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.5
     steps:
       - checkout
       - run: pip install -e .
       - run: pip install -e .[tests]
       - run: pytest tests/unit_tests